[package]
name = "rust-function-template"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
extism-pdk = "1.4.1"
rust_decimal = "1.37.2"
serde = "1.0.219"
serde_json = "1.0.143"
